---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - nginx

- name: Ensure nginx is installed.
  yum: pkg=nginx state=installed enablerepo=nginx
  tags:
    - nginx

- name: copy nginx default conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx
  tags:
    - nginx

- name: copy nginx default site
  template: src=default.{{ nginx.php_engine }}.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx
  tags:
    - nginx

- name: create document root directory if needed
  file: path={{ nginx.document_root }} state=directory mode=0755
  tags:
    - nginx

- name: copy phpinfo
  template: src=index.php.j2 dest={{ nginx.document_root }}index.php
  notify: reload nginx
  tags:
    - nginx
